`some_col0` STRING,
`some_col1` STRING,
`col0` DOUBLE,
`col1` STRING,
`col2` DATE,
`col3` TIMESTAMP,
`some_col2_UTSucceedIfInOutput` STRING,
`some_col3_UTSucceedIfInOutput` STRING,
`some_col4_UTSucceedIfInOutput` STRING